//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glorg2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glorg2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;material&gt;
        ///	&lt;VertexShader&gt;
        ///	#version 140
        ///
        ///	uniform mat4 projection_mat;
        ///	uniform mat4 modelview_mat;
        ///	
        ///
        ///	in vec4 in_position;
        ///	in vec2 in_texcoord0;
        ///	in vec3 in_normal;
        ///
        ///	out vec4 position;
        ///	out vec3 normal;
        ///	out vec2 texcoord;
        ///	void main()
        ///	{	
        ///		position = projection_mat * modelview_mat * in_position;
        ///		gl_Position = position;
        ///		normal = in_normal;
        ///		texcoord = in_texcoord0;
        ///	} 
        ///	&lt;/VertexShader&gt;
        ///
        ///	&lt;FragmentShader&gt;
        ///	#version 140
        ///	uniform samp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultMaterial {
            get {
                return ResourceManager.GetString("DefaultMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;material&gt;
        ///	&lt;VertexShader&gt;
        ///	#version 140
        ///
        ///	uniform mat4 projection_mat;
        ///	uniform mat4 modelview_mat;
        ///	
        ///
        ///	in vec4 in_position;
        ///	in vec2 in_texcoord0;
        ///	
        ///
        ///	out vec4 position;
        ///	out vec3 normal;
        ///	//out vec2 texcoord;
        ///	void main()
        ///	{	
        ///		position = projection_mat * modelview_mat * in_position;
        ///		gl_Position = position;
        ///		normal = in_normal;
        ///		texcoord = in_texcoord0;
        ///	} 
        ///	&lt;/VertexShader&gt;
        ///
        ///	&lt;FragmentShader&gt;
        ///	#version 140
        ///	uniform sampler2D diffuse_te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SkydomeMaterial {
            get {
                return ResourceManager.GetString("SkydomeMaterial", resourceCulture);
            }
        }
    }
}
